{{- if .Values.excalidraw.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-secret-env-excalidraw-room
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.commonSecretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}

  {{- range $key, $val := .Values.excalidraw.excalidrawRoom.secretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
