name: Deploy to workadventure.iits.tech
on:
  push:
    branches: [master, develop]
jobs:
  deploy-iits-cluster:
    name: "Deploy to azure iits cluster"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out argocd azure
        uses: actions/checkout@master
        with:
          repository: iits-consulting/azure-charts
          token: ${{ secrets.ARGO_CD_WITH_DEPLOYMENT_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Push new Git Version
        env:
         APP: "workadventure"
         CI_ENVIRONMENT_NAME: "azure"
        run: |
          ARGOCD_PROJECT_NAME=azure-charts
          APP=$(echo "${PWD##*/}")

          ls
          cd projects/azure-charts/helm-charts/$APP

          printf "helm:\n  parameters:\n  - name: image.tag\n    value: ${{ steps.vars.outputs.sha_short }}" > .argocd-source-$APP.yaml

          git config user.email "github@iits-consulting.de"
          git config user.name "Github"
          git add .
          git commit -m "$CI_ENVIRONMENT_NAME: $APP updated to ${{ steps.vars.outputs.sha_short }}"
          git push